name: SQL check
on: pull_request

jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: yokawasa/action-sqlcheck@v1.4.0
        with:
          risk-level: 3
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}
